controller_manager:
  ros__parameters:
    update_rate: 100

    simple_omni_wheel_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

simple_omni_wheel_controller:
  ros__parameters:
    joints:
      - wheel_1_joint
      - wheel_2_joint
      - wheel_3_joint
    
    interface_name: velocity
    
    command_interfaces:
      - velocity
    
    state_interfaces:
      - position
      - velocity

joint_state_broadcaster:
  ros__parameters: {}
