#!/usr/bin/env python3
"""
Web Terminal Node - ROS2 Integration Node
Interact with MissionPlanner through bot_cmd_interface

Architecture Design:
- Persistent listener on /cmd/response (passive receiving, not active polling)
- All responses delegated to TaskManager for processing (intelligent matching by task_id/request_id)
- WebSocketHandler only responsible for broadcasting updates to frontend
"""

import rclpy
from rclpy.node import Node
from std_msgs.msg import String
from typing import Optional

from bot_cmd_interface.sdk import (
    CommandRequest,
    CommandResponse,
    ResponseStatus,
    ErrorCode,
    create_navigate_request,
    create_exploration_request,
    create_patrol_request,
    create_get_status_request,
    create_cancel_task_request,
    create_emergency_stop_request,
)


class WebTerminalNode(Node):
    """Web Terminal Node - Responsible for ROS2 communication and CMD message routing"""
    
    def __init__(self, task_manager, websocket_handler):
        """
        Initialize node
        
        Args:
            task_manager: TaskManager instance (handles task status updates)
            websocket_handler: WebSocketHandler instance (broadcasts updates to frontend)
        """
        super().__init__('web_terminal_node')
        
        self.task_manager = task_manager
        self.websocket_handler = websocket_handler
        self._shutdown_flag = False
        
        # Publisher: send command requests to /cmd/request
        self.cmd_publisher = self.create_publisher(
            String,
            '/cmd/request',
            10
        )
        
        # Subscriber: receive command responses from /cmd/response
        self.cmd_subscriber = self.create_subscription(
            String,
            '/cmd/response',
            self._response_callback,
            10
        )
        
        self.get_logger().info('Web Terminal Node initialized')
    
    def _response_callback(self, msg: String):
        """
        Handle responses from /cmd/response (persistent listener)
        
        Architecture core: Passively receive all responses, delegate to TaskManager for intelligent processing
        - TaskManager matches tasks based on task_id/request_id
        - Unrelated responses are automatically ignored (not in cache)
        - Completely asynchronous, does not block ROS2 thread
        """
        try:
            # 使用 SDK 反序列化
            response = CommandResponse.from_json(msg.data)
            
            self.get_logger().debug(
                f"收到响应: request_id={response.request_id}, "
                f"status={response.status}, code={response.code}"
            )
            
            # 委托给 TaskManager 处理（智能匹配）
            response_dict = {
                'header': {'request_id': response.request_id},
                'body': {
                    'status': response.status.value if hasattr(response.status, 'value') else response.status,
                    'message': response.message,
                    'data': response.result if hasattr(response, 'result') else {},
                    'error_code': response.code.value if hasattr(response.code, 'value') else response.code
                }
            }
            
            updated_task = self.task_manager.update_task(response_dict)
            
            # 如果任务更新成功，通过 WebSocket 广播给前端（使用同步版本）
            if updated_task:
                self.websocket_handler.broadcast_task_update_sync(updated_task.to_dict())
                self.get_logger().info(
                    f"✓ 任务更新: {updated_task.request_id} -> {updated_task.status}"
                )
            
        except Exception as e:
            self.get_logger().error(f"处理响应失败: {e}")
    
    def _publish_request(self, request: CommandRequest) -> str:
        """
        Publish request to /cmd/request
        
        Returns:
            request_id: Request ID automatically generated by SDK
        """
        try:
            # Use SDK to serialize
            msg = String()
            msg.data = request.to_json()
            
            # Publish to /cmd/request
            self.cmd_publisher.publish(msg)
            
            request_id = request.request_id
            self.get_logger().info(f"Request sent: request_id={request_id}")
            
            return request_id
            
        except Exception as e:
            self.get_logger().error(f"Failed to send request: {e}")
            raise
    
    # ============================================
    # Public API methods (called by FastAPI)
    # ============================================
    
    def navigate_to_pose(self, x: float, y: float, yaw: float = 0.0) -> str:
        """
        发送导航到指定位姿的命令
        
        Args:
            x: 目标 X 坐标
            y: 目标 Y 坐标
            yaw: 目标朝向（弧度）
            
        Returns:
            request_id: 请求 ID（用于后续查询状态）
        """
        request = create_navigate_request(x=x, y=y, yaw=yaw)
        return self._publish_request(request)
    
    def start_exploration(
        self,
        map_name: Optional[str] = None,
        save_on_completion: bool = True
    ) -> str:
        """
        Send command to start exploration and mapping
        
        Args:
            map_name: Map name (optional)
            save_on_completion: Whether to save map on completion
            
        Returns:
            request_id: Request ID
        """
        request = create_exploration_request(
            map_name=map_name,
            save_on_completion=save_on_completion
        )
        return self._publish_request(request)
    
    def start_patrol(
        self,
        waypoint_file: str,
        mode: str = "loop"
    ) -> str:
        """
        Send command to start patrol
        
        Args:
            waypoint_file: Waypoint file path
            mode: Patrol mode (loop/once/bounce)
            
        Returns:
            request_id: Request ID
        """
        request = create_patrol_request(
            waypoint_file=waypoint_file,
            mode=mode
        )
        return self._publish_request(request)
    
    def query_task_status(self, task_id: Optional[str] = None) -> str:
        """
        Query task status
        
        Args:
            task_id: Task ID (optional, query all tasks if None)
            
        Returns:
            request_id: Request ID
        """
        request = create_get_status_request(task_id=task_id)
        return self._publish_request(request)
    
    def cancel_task(self, task_id: str) -> str:
        """
        Cancel task
        
        Args:
            task_id: Task ID
            
        Returns:
            request_id: Request ID
        """
        request = create_cancel_task_request(task_id=task_id)
        return self._publish_request(request)
    
    def pause_task(self, task_id: str) -> str:
        """
        Pause task
        
        Args:
            task_id: Task ID
            
        Returns:
            request_id: Request ID
        """
        from bot_cmd_interface.sdk import ActionType
        
        request = CommandRequest(
            action=ActionType.PAUSE_TASK,
            params={'task_id': task_id},
            priority=2,
            timeout=5.0
        )
        return self._publish_request(request)
    
    def resume_task(self, task_id: str) -> str:
        """
        Resume task
        
        Args:
            task_id: Task ID
            
        Returns:
            request_id: Request ID
        """
        from bot_cmd_interface.sdk import ActionType
        
        request = CommandRequest(
            action=ActionType.RESUME_TASK,
            params={'task_id': task_id},
            priority=2,
            timeout=5.0
        )
        return self._publish_request(request)
    
    def emergency_stop(self) -> str:
        """
        Emergency stop
        
        Returns:
            request_id: Request ID
        """
        request = create_emergency_stop_request()
        return self._publish_request(request)
    
    def spin(self):
        """Run node (called in separate thread)"""
        while rclpy.ok() and not self._shutdown_flag:
            rclpy.spin_once(self, timeout_sec=0.1)
    
    def shutdown(self):
        """Shutdown node"""
        self._shutdown_flag = True
        self.get_logger().info('Web Terminal Node shutting down...')
        self.destroy_node()
